name: subscribe
on:
  issues:
    types: [opened, edited, reopened]
permissions:
  issues: write
jobs:
  subscribe:
    if: contains(github.event.issue.labels.*.name, '구독신청') && github.event.issue.state == 'open'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install jq

      - name: Set execute permission for script
        run: chmod +x ./scripts/subscribe.sh

      - name: subscribe
        continue-on-error: false
        run: |
          ./scripts/subscribe.sh "${{ github.event.issue.body}}" "${{ secrets.API_GATEWAY_URL }}"
